name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Android SDK components
      uses: android-actions/setup-android@v2

    - name: Accept Licenses
      run: yes | sdkmanager --licenses

    - name: Install specific NDK version
      run: sdkmanager "ndk;29.0.13113456"

    - name: Set up NDK path
      run: echo "ndk.dir=$ANDROID_SDK_ROOT/ndk/29.0.13113456" >> local.properties

    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace --info --no-daemon

      - name: Cache Gradle
  uses: actions/cache@v3
  with:
    path: |
      ~/.gradle/caches
      ~/.gradle/wrapper
    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
    restore-keys: |
      ${{ runner.os }}-gradle-

